name: svg_flag
description: A curated collection of all country flags in SVG format for easier integration.
version: 1.5.1
homepage: https://inidia.app
repository: https://github.com/Nialixus/svg_flag.git
issue_tracker: https://github.com/Nialixus/svg_flag/issues
funding: 
  - https://ko-fi.com/nialixus
screenshots:
  - description: 'Svg Flag Logo'
    path: logo.png
topics:
  - flag
  - svg
  - icon
  - asset

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  assets:
    - assets/